"""Added is authenticated at User Table

Revision ID: 074891e4827d
Revises: 9bb6fc1dbde1
Create Date: 2019-03-10 10:17:41.382346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074891e4827d'
down_revision = '9bb6fc1dbde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('IsAuthenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'IsAuthenticated')
    # ### end Alembic commands ###
