"""empty message

Revision ID: 1b7689111e21
Revises: 2b7fe95b63e0
Create Date: 2019-06-07 00:48:58.700167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7689111e21'
down_revision = '2b7fe95b63e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotelbookings', sa.Column('PaymentMethod', sa.Integer(), nullable=True))
    op.add_column('packagebookings', sa.Column('PaymentMethod', sa.Integer(), nullable=True))
    op.add_column('ticketbookings', sa.Column('PaymentMethod', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticketbookings', 'PaymentMethod')
    op.drop_column('packagebookings', 'PaymentMethod')
    op.drop_column('hotelbookings', 'PaymentMethod')
    # ### end Alembic commands ###
