"""empty message

Revision ID: 2b7fe95b63e0
Revises: dc316d4f9c44
Create Date: 2019-06-01 14:10:01.313187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7fe95b63e0'
down_revision = 'dc316d4f9c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('PaymentMethod', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'PaymentMethod')
    # ### end Alembic commands ###
