"""Added date created and date updated in Package Table

Revision ID: 4fc51ea4fa3d
Revises: cf628738ff0b
Create Date: 2019-02-25 00:11:37.744468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc51ea4fa3d'
down_revision = 'cf628738ff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('DateCreated', sa.DateTime(), nullable=True))
    op.add_column('packages', sa.Column('DateUpdated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'DateUpdated')
    op.drop_column('packages', 'DateCreated')
    # ### end Alembic commands ###
