"""empty message

Revision ID: 684e38e8936b
Revises: d3273cee919e
Create Date: 2019-06-24 06:48:24.343259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684e38e8936b'
down_revision = 'd3273cee919e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packagebookings', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packagebookings', 'IsArchived')
    # ### end Alembic commands ###
