"""Fixed relationships

Revision ID: 8c8b3fe8a211
Revises: 4fc51ea4fa3d
Create Date: 2019-02-25 16:37:13.991336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8b3fe8a211'
down_revision = '4fc51ea4fa3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotelbookings_CustomersFk_fkey', 'hotelbookings', type_='foreignkey')
    op.create_foreign_key(None, 'hotelbookings', 'users', ['CustomersFk'], ['Id'])
    op.drop_constraint('packagebookings_CustomersFk_fkey', 'packagebookings', type_='foreignkey')
    op.create_foreign_key(None, 'packagebookings', 'users', ['CustomersFk'], ['Id'])
    op.drop_constraint('ticketbookings_CustomersFk_fkey', 'ticketbookings', type_='foreignkey')
    op.create_foreign_key(None, 'ticketbookings', 'users', ['CustomersFk'], ['Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticketbookings', type_='foreignkey')
    op.create_foreign_key('ticketbookings_CustomersFk_fkey', 'ticketbookings', 'customers', ['CustomersFk'], ['Id'])
    op.drop_constraint(None, 'packagebookings', type_='foreignkey')
    op.create_foreign_key('packagebookings_CustomersFk_fkey', 'packagebookings', 'customers', ['CustomersFk'], ['Id'])
    op.drop_constraint(None, 'hotelbookings', type_='foreignkey')
    op.create_foreign_key('hotelbookings_CustomersFk_fkey', 'hotelbookings', 'customers', ['CustomersFk'], ['Id'])
    # ### end Alembic commands ###
