"""Fixing Inquiry Customer Table

Revision ID: 9bb6fc1dbde1
Revises: 8c8b3fe8a211
Create Date: 2019-03-04 18:39:59.447991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb6fc1dbde1'
down_revision = '8c8b3fe8a211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flightinquiries', sa.Column('CustomersFk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flightinquiries', 'users', ['CustomersFk'], ['Id'])
    op.drop_column('flightinquiries', 'lastName')
    op.drop_column('flightinquiries', 'Email')
    op.drop_column('flightinquiries', 'FirstName')
    op.add_column('hotelinquiries', sa.Column('CustomersFk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotelinquiries', 'users', ['CustomersFk'], ['Id'])
    op.drop_column('hotelinquiries', 'lastName')
    op.drop_column('hotelinquiries', 'Email')
    op.drop_column('hotelinquiries', 'FirstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotelinquiries', sa.Column('FirstName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hotelinquiries', sa.Column('Email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hotelinquiries', sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hotelinquiries', type_='foreignkey')
    op.drop_column('hotelinquiries', 'CustomersFk')
    op.add_column('flightinquiries', sa.Column('FirstName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('flightinquiries', sa.Column('Email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('flightinquiries', sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flightinquiries', type_='foreignkey')
    op.drop_column('flightinquiries', 'CustomersFk')
    # ### end Alembic commands ###
