"""empty message

Revision ID: d3273cee919e
Revises: 1b7689111e21
Create Date: 2019-06-13 18:35:11.100262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3273cee919e'
down_revision = '1b7689111e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CustomersFk', sa.Integer(), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['CustomersFk'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###
