"""new table structure

Revision ID: dc316d4f9c44
Revises: be5c62a36285
Create Date: 2019-03-15 05:46:47.806560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc316d4f9c44'
down_revision = 'be5c62a36285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Itinerary', sa.String(length=255), nullable=True),
    sa.Column('PackageFk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PackageFk'], ['packages.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_column('users', 'Username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('itinerary')
    # ### end Alembic commands ###
