"""empty message

Revision ID: e6fbe446e521
Revises: 653eb08ddd89
Create Date: 2019-07-05 04:51:17.947455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fbe446e521'
down_revision = '653eb08ddd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('Extension', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'Extension')
    # ### end Alembic commands ###
